services:
  - type: worker
    name: forex-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python trading_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false